server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug" # debug, release, test
  read_timeout: 30
  write_timeout: 30

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  database: "ruixin_platform"
  username: "test"
  password: "!QAZzse4"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "ruixin_platform_jwt_secret_key_2025"
  expiration: 86400 # 24 hours

luckin:
  base_url: "https://lkcoffe.cn"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
  timeout: 30
  max_retries: 3
  headers:
    accept: "*/*"
    accept-language: "zh-CN,zh;q=0.9"
    cache-control: "no-cache"
    pragma: "no-cache"
    sec-ch-ua: '"Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"'
    sec-ch-ua-mobile: "?0"
    sec-ch-ua-platform: '"Windows"'
    sec-fetch-dest: "empty"
    sec-fetch-mode: "cors"
    sec-fetch-site: "same-origin"

log:
  level: "info"
  filename: "logs/ruixin.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true